account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    
    path("", views.startPage, name="index"),
    path("transaction_page/", views.transactionPage, name="transact"),
    path("create_account/", views.createAccount, name="createAccount"),
    path('transaction/', views.transaction, name='transaction'),
    path("get_balance/<int:account_id>/<str:amount>", views.getBalance, name="getBalance"),
    path("withdraw/<int:account_id>/<str:amount>", views.withdraw, name="withdraw"),
    path("deposit/<int:account_id>/<str:amount>", views.deposit, name="deposit"),
    
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("account.urls"))
]

account/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    customer_id = models.IntegerField()
    account_id = models.IntegerField()
    balance = models.IntegerField(default="0")

    def __str__(self):
        return f"Account: {self.account_id}"

class Withdraw(models.Model):
    account = models.ForeignKey(Account, related_name='withdrawals', on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"Withdraw: {self.amount}"


class Deposit(models.Model):
    account = models.ForeignKey(Account, related_name='deposits', on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"Deposit: {self.amount}"

account/forms.py
from django import forms

from .models import Account

account/views.py
from django.shortcuts import (render, get_object_or_404, HttpResponseRedirect)
from .models import Account, Withdraw, Deposit
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
import datetime
from django.contrib import messages
from django.http import HttpResponse



# Create your views here.
#index
def startPage(request):
    
    return render(request, 'pages/index.html')

def transactionPage(request):
    return render(request, 'pages/transactionPage.html')

    

# createAccount
def createAccount(request):
    latest_account = Account.objects.order_by('-customer_id').first()
    if latest_account:
        next_customer_id = latest_account.id + 1
    else:
        next_customer_id = 1

    balance = 0
    account = Account.objects.create(customer_id=next_customer_id, account_id=next_customer_id, balance=balance)
    account.save()
    context ={
        "customer_id": next_customer_id,
        "account_id": next_customer_id,
        "balance": balance,
        "account": account
    }
    return render(request, 'pages/transactionPage.html', context)

    
#transaction
def transaction(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        amount = request.POST.get('amount')
        account_id = request.POST.get('account_id')
        
        
        print(account_id)
        print(amount)

        if action == 'deposit':
            deposit(request, account_id, amount)
        elif action == 'withdraw':
            withdraw(request, account_id, amount)
                
        account = Account.objects.filter(account_id=account_id).first()
        
        messages.get_messages(request)

        context ={
            "action": action,
            "amount": amount,
            "account_id": account_id,
            "customer_id": account.customer_id,
            "balance": account.balance,     
        }

    return render(request, 'pages/transactionPage.html', context)

#get_balance API 
def getBalance(request, account_id, amount):
    account = Account.objects.filter(account_id=account_id).first()
    
    if account:
        context ={
            "balance": account.balance,
        }
        messages.success(request, f"Your current balance is {{account.balance}} successful.")
        return render(request, 'pages/transactionPage.html', context)
    else:
        messages.error(request, "Account does not exist")
        return render(request, 'pages/transactionPage.html')
    
#withdraw API
def withdraw(request, account_id, amount):
    account = Account.objects.filter(account_id=account_id).first()
    withdrawals = Withdraw.objects.filter(account=account, date=timezone.now().date())
    
    if withdrawals.count() >= 3:
        messages.warning(request, "Exceeded Maximum number of withdrawals(3) per day")
        return render(request, 'pages/transactionPage.html')
        
    
    if account is None and amount is None:
        messages.error(request, "Invalid withdrawal amount. Kindly enter a figure.")
        return render(request, 'pages/transactionPage.html')
    
    if float(amount) > 20000:      
        messages.warning(request, "Exceeded Maximum Withdrawal Per Transaction")
        return render(request, 'pages/transactionPage.html')
    
    if account.balance < float(amount):
        messages.error(request, "Insufficient Balance")
        return HttpResponse(status=404)

        # return render(request, 'pages/index.html')
    
    today_withdrawals = Withdraw.objects.filter(account=account, date=timezone.now().date()).values_list('amount', flat=True)

    total_withdrawals= sum(today_withdrawals)
    
    if total_withdrawals + float(amount) > 50000:
        messages.warning(request, "Exceeded Maximum Withdrawal for the day")
        return render(request, 'pages/transactionPage.html')
    
    withdraw = Withdraw.objects.create(account=account, amount=amount)
    account.balance -= float(amount)
    account.save()
    withdraw.save()
    
    messages.success(request, "Withdrawal request received. Processing...")
    return render(request, 'pages/transactionPage.html')

#Deposit API
def deposit(request, account_id, amount):
    account = Account.objects.filter(account_id=account_id).first()
    deposit = Deposit.objects.filter(account=account, date=timezone.now().date())
    
    if deposit.count() >= 4:
        messages.warning(request, "Exceeded Maximum number of deposit(4 deposits) per day")
        return render(request, 'pages/transactionPage.html')
        
    if account is None and amount is None:
        messages.error(request, "Invalid deposit amount")        
        return render(request, 'pages/transactionPage.html')
    
    if int(amount) > 40000:
        messages.warning(request, "Exceeded Maximum Deposit(KES 40K) Per Transaction.")
        return render(request, 'pages/transactionPage.html')
    
   
    today_deposit = Deposit.objects.filter(account=account, date=timezone.now().date()).values_list('amount', flat=True)

    total_deposit= sum(today_deposit)
    
    if total_deposit + int(amount) > 150000:
        
        messages.warning(request, "Exceeded Maximum deposit(KES 150K) for the day.")
        return render(request, 'pages/transactionPage.html')
    
    deposit = Deposit.objects.create(account=account, amount=amount)
    account.balance += int(amount)
    account.save()
    deposit.save()
    
    context ={
        "customer_id": account_id,
        "account_id": account_id,
        "account": account
    }
    messages.success(request, "Deposit request received. Processing...")
    return render(request, 'pages/transactionPage.html', context)




    

        
    
    
    
        

account/templates/pages/index.html
{% extends 'pages/layout.html' %}

{% block body %}
<div class="card text-center">
  
  <h3 style="font-weight: bold;"> Welcome Customer!</h3>
  <br>
  <div>
    <a href="{% url 'account:createAccount' %}" class = "btn btn-primary">Open Account to proceed</a>
  </div>
  <br>
</div>
<br>
{% endblock body %}

  

account/templates/pages/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/brands.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <style>
            .container {
            
                position: absolute;
                left: 50%;
                top: 50%;
                bottom: 50%;
                transform: translate(-50%, -50%);
                height: 100%;
                display: block;
                justify-content: center;
                align-items: center;
                
              }
            .message-success {
                color: green;
            }
            
            .message-error {
                color: red;
            }
            
            .message-info {
                color: blue;
            }
            
            .message-warning {
                color: orange;
            }
            

        </style>
    </head>
    <body class = "bg-light">
        
        <div class="container">
            <div class="row mt-5">
                <div>
                    <div  class="card"  style:"align_items: center; justify-content:center;">
                        <div class="card-header shadow-sm bg-white">
                            <h1 class="displa-5 text-info" onclick="window.location.href='{% url 'account:index'%}'"><i class=""></i>Bank App Project</h1>
                        </div>
                        <div class="card-body">
                            {% block body %}
                            

                            {% endblock body %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        
        <script src="" async defer></script>
    </body>
</html>

account/templates/pages/transactionPage.html
{% extends 'pages/layout.html' %}

{% block body %}
<div class="card text-center">
  
  <h2 style="font-weight: bold;"> Customer Details</h2>
  <p>Customer ID: {{ customer_id}} </p>
  <p>Account ID: {{account_id}}</p>
  <p><strong>Balance: {{balance}} KES </strong></p>

</div>
<br>
  
<div class="card text-center">
  <div class="card-header">
    <h3 style="font-weight: bold;">
      Transaction Instructions
    </h3>
  </div>
  <div>
    <p>Enter a valid amount for deposit or withdrawal.</p>
    <p>Deposit limits: Max per transaction: Kes. 40K, Max frequency: 4 transactions/day, Max for the day: Kes. 150K</p>
    <p>Withdrawal limits: Max per transaction: Kes. 20K, Max frequency: 3 transactions/day, Max for the day: Kes. 50K</p>
  </div>
  
</div>
<br>
<div class="card text-center">
  <div>
    <form method="post" action="{% url 'account:transaction'%}">
      {% csrf_token %}
      
      <div class="form-group">
          <label for="id_amount"><strong>Enter Amount:</strong></label>
          <input type="number" class="form-control" name="amount" maxlength="100" required id="id_amount">
      </div>
      <input type="hidden" class="form-control" name="account_id" maxlength="100" required id="id_account_id" value="{{ account_id }}">
      <br>
      <button type="submit" class="btn btn-success" name="action" value="deposit">Deposit</button>
      <button type="submit" class="btn btn-primary" name="action" value="check_balance">Check Balance</button>
      <button type="submit" class="btn btn-danger" name="action" value="withdraw">Withdraw</button>
      <br>
      <br>
  </form>
  </div>
</div>
<div class="card text-center">
  <div>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
            <li class="message-{{ message.tags }}">{% if message.tags %}{{ message.tags }}: {% endif %}{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

  </div>
</div>

{% endblock body %}

  